language: node_js
node_js:
- '8'
sudo: false
before_script:
- npm install -g quasar-cli
script:
- quasar lint
- quasar build
cache:
  directories:
  - node_modules
addons:
  ssh_known_hosts:
  - bangdream.ga
  - bandori.tech
  sauce_connect:
    username: DNARoma
  jwt:
    secure: 'YKs+ldejsnnnqr6JzqzaaEFzGJDhI6t3WEZcxKUuvKXNDcIMxscAKDah0ybVX9OyzmKgGPNvFVPx1GcpbpjpR8p6iLfQd4V1+SQH8PK2Ays7ovWtWlv1WXBMk23usVjv+P+n54gX+q1pjPINMPf/wMekcAmpDOfKFOe+kVzqKYkUCra++onyYU1O2Q6tIPdvCcBivjJM6b4SyC/uG78rUCEMLT7WhTac4k+LPitldfrdgYyN32fDuYoyAU11nCgR7ATFgaQGNAuJ78wWpPG+/gzYeRYxkcOhJNhRAODfauZoD+0jQNbFTBhS6YRrUZv6r0G8ZXUhHkVKONHc82RhdTYY9febPcUnlBVGdO15OeNJy0vfJ+Fl1R7iiwR3puEtBFYCWIAB+tYKbG8xKb44RH/vG4YQbcu3Zs71Mz39CIpM5qI8RHQAV7fDwmS3NW0XgK0zyh9lKM+QuJATscRhSan0+QOI87k7euBBHs2lh1f4DGxui8CVByDeKxEGGBE56wfI317lM9bynem4KHMIYik1Oy/EEl0UhtM11rrmpdVx00p9Q//JUxiHVkFyCSYMq1qeeehuHMxEYBD6mP9wudUdrQbwbG3b1Vk/dS75KrEbFHgrZm6ooImvYSGcwbJgwkVEP5R+/oyItMnlzBaeYHhCqxezJ5grwgZIR3Do4Pc= '
before_deploy:
- openssl aes-256-cbc -K $encrypted_6471c10cdc2d_key -iv $encrypted_6471c10cdc2d_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: sh build/deploy.sh
  on:
    branch: master
env:
  global:
  - secure: ZnAcxOTZJQCkeH99+iXffTOxukbcKTHulywDUMnl4DD4Ms8JcQx7izssfQgTChUDLfxdxU8zb961rF/4brXS/MWSO0mkDMWcvscb6XF1Nc8k0FR7EtzgEwUq9t7X5OitrxIn5j5Z+USBjhiYAOm7DrrFSctKtt7H0Gmd0nf5qeZn3qOxBC+33IQ/FhaO5kZD1M4nnkBDwLJwlUwAbbuXnZootAMPdBSZ0GU8NDiaAl4V96z80YRZJLDWh6pY+Dqh6weE6iDhBUZcGc7794kOB/WId/AxAGRNlaOrV9Ed2NHQ/H8Bmh0wSGoeMSaXYWYUoE9F0Ry6Bl4JJPDydTCFTbG3+XIcn8RomaYmwTIotZgCL4zOyM4gT1C/yT8BsvNelYcfmYW3FiZ1XH29F7y4/oZH0lB5EXTNsbjJTlFm4/xRE6AN0Q/NbxytdKIp5FsNil6GE+xHmFPOHqv6gF3pdMS0XL7MOH/pz4Zs121Co3ATEpthH718jM7cW7xYKUstAEbJ/Sfpm46of7a3uDyabQPC1WHNr6kMhzhoot3MGtnCYHFRLOccL5MN1FpGee63mgBTFS8Y1mi3EhADmi4ToYwSJWBYhhKc6pZCveWJ2LoKsDpOz/Ox8pKmKZZ/vlY/qw8Bdf2Zr5iISHPpKxl8SAmnioCN+TMx2UeNjIinlkU=
  - secure: BPRH89k3bObpavoqMClrj07QrNiFzffZqINo9WSTT+OgqgwBWauaCqmM8WZBpC456MjKx/dd/sagazFd1hhSqyndGoRFVapGfNabjmVX8507hRC++podUeiHpat8vySMCG4MA9E13JTvAnEoilPMBHIbpBfbEbhEYMXGYsKcriMau4Bm8xarKN2SBA8/u6yegZw8RvninBayKRI3A5I+wVdem2lZzBN80cJJ9nnSZPbhgG5X+jiX+A/vuWRfmXs0UEBE5Pl4/KV1yOOIQDm8SqwPR/z7Ru3dqZa6Ns21DQQGB7E3x1JyQPrHUafu19MOgVpzix0vu1+bX6g5wT1IynHgofWG1BvFsrnGIFJozSUaZGYOOWsu/DdcDzhipSboLV5m/WTsCSm71z334rrQ1y44lIKqWFR0vomzY29vFcyDL1r2WyUKaKsGS7NGJ2o2gOcIOYhCehuO7pT1nGxWC0tSs88xZaIvjG0ygZEOKWEXDB4bu9FRGgVv3XIohNULv1aDvBCKZtLCn6L7lL71zrCuRmjtVHt+o5cfQ9k+l51f1aZk+447c/LElyFjAAo20j/1TKdhjPUFTuI20W/s/ZLLe2jbNeM9YJZ5roEudUzOKBaapDtPAxBcqQNbY1bMlZudonkgjgzK1N0t1GUsiTWFzeW9dHUbeOqaszbiuFk=
  - secure: UDVPfnXtRN9u5/nsXkuD8QTpFX1CBorjiM02u3nMSPKy4qw2Bn6/FyPe0Gl4/gi+1XOWt6dGfqIvpkVGTYygLUrikqSE2JrKRXbUGiwP/zFNQ2XmcGcwosZq25fp8dU+FYpBbDOJLKuPwUCwk0Y2QekXlccQbDYEpqFv6viKrRx6q92ldYKnCTGBiEfl7qJMNaM4mzTmf45FhULuiN1QTq6zudg7EnMHwO5naRfPAlaZxFqVFvmfZQ6TBbXX9/cuFezAY0Ga0fb/mELe8JLh565oF/RMd0RZKMU913OztHlLMrDqy0OBGBIn8JIK5ruxm0sQiXrtsRrHZe9/VJZ25ET/fLYj8NegowY2561E4NcUtoEukDtOZlQqK80a6KKABXZtnNfCKUvC/easDUo3w0qZXDqoai6VIUBaY9vb5YA7Jolrctku8+U57iR27p/2MMpnss59Aw8r9OirVQEbsy+6mbfI+jxE/qlP8EHevo8/0Ue9jjJXEZBUrhBBvLqiVhYRDA6L+rbaVwO25Q2ep0IpT9erea37HAw4Drh0Mg2i3qQ5nLKKDC3iOMh/wRea6O+DmWTY/3/43kmV9s+AXCWTNtbWd61dMtlgcburJueIFzifFQoUunw9KKgV41AklfmGMySpgZo60mYCfeapWDDnQGQy+xozXZpVnjB7Mdg=
  - secure: KHM3x0xn1Y0SCcFCfOYBBbEEG2fqXKdWvUR8CgqLMyAD4d/rGY67rKqlQZHXoFPogFTBDwgsb2UptjozAUey8FyfZKLQxO0Ycykat61mcIul8sDFR/fVP+RYUNp9iPfjLBGDxvHl9GOJ/11XtzTLo4CGsrtiTJIK8PNxR8qRL/lqwq2oiw+0VQqul80N000XpXWatc/LRliToK7Dh+j4n1nUQvU7schv1xBKgAXvhGOZApyC0QK1HPQHYyDVSipxlVNgPd/2xRebnSSL734KEuhY99EffWJmDjGO2enUfjWH5T0whX9CdyGP+8oOA3vfWOQm/oTg15s53VVrhiogO+TFWgX3UwVtOf8QjWxhlnYZSrL4we1O+A0I2euAr/HIpnoAxFg1raqVHiqmowzRmkES+7jrT5MJnw90M8cKyVYz+zQs5nZwCuVCRp2wv7asATfwB+uE2n9DHGbiyrJ7TQ+Z8bEqElol0eJwwQ6A2YBr8+h2R82tXG/ewaT7t7qahvF00hiX5mCUk3Bw4SORq+e0QjJZCMNCwXeld9HEGfJsZHd9sxr/K2YhuTBxln5JEW9pZHJK12ryKO3PDvmZj49uK4IanNGLkkRI/VZH3xmRh577vbm+jW39MIqsHIIE6NPI69YyrlsoadpysEfjLmb2gtM3JtOPDu7SeW1hNuE=
