language: node_js
node_js:
- '8'
sudo: false
before_script:
- npm install -g quasar-cli
script:
- quasar lint
- quasar build -m pwa
before_deploy:
- openssl aes-256-cbc -K $encrypted_6471c10cdc2d_key -iv $encrypted_6471c10cdc2d_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: sh ./deploy.sh
  on:
    branch: master
env:
  global:
  - secure: IMWC3X7hkMHTLB/9Nw6VZGdD8R1BT0O3elFTHz9oRbS3NamrZZ3rGOY5ZbH2P3Gx5RJH7Y8L67Hg/Ea93rIssMaDk28BxDvU7btQQWDHLQAvZ2BqOtxb5Ikr2uz28uVcXNNmSiRYWFdONHs31pITGnMxljkM39IPBZxTROzNnEMxGa1Y6EQA5eki4PNRSw1EN9b/5v5SQXOCEUKu+PzoIcT6j7MqlpWp3inWremiSg9BO7iDX6+/aZGD1ROnWy07fmS3Mw2yadCFKPkChDgxdu/C92vtRc/ReAijT7/nMH9FqH6okTqCSaTiBpgqnRJEHNXT+v28KHEcsjW2BTiVtUaP1MbDdXFBtcx6gjjLmBpxKpjaDKS6Iel6FHtsicLkAVNrV4VOYIf1zGbsyGqRyzqJkaxxA5xWt2FEdZlDBFGnmOWtwLrzSnJNdds/ccwOS4c77H4LtGwWp8PHjKJnOTqhesbhilMKV3kLELhwjlfc5mtxOjoiO+LE682f20g+Ek+gKnwWCuNU2aGdbUcJe8BdYziQS1vZFK6Z/baijhvH+Y/uD1vvP9eUyUl4Y7fYQ041t5w0bdYzGov9CL4ar9Bu3dgwA2vUou9zDcJnh0D0fYm1Ke4FpZ645FHPcAVrZQrcEP4LQYSTt168UPT/kQaA8fIllhNwweYe0AxMI4w=
  - secure: a0tvpdA24PxvWCWWrSbChU70franokgmxQWSuklmKVP8PVLQFMG6dOs739Vn0ikkr60cNEAVgoDqgKWyQOTHbCb9rJGz3A7JQtwG1dMSfxdEfJxYU85URoA74OSrWLS6pvh352W0sKnKx+7XSYZl6T47VYBUAA6B4IhpSe/eRbE/Dc8RCSSH2PlrDjHn0iMYGKPHBHjMMCSL62GvrMhw8lnCCx3RnTYkyUzRjFC8ONvEiWfdDKhICC8BjBPnES3BATEfj+2bqFvWT2/rbTCVRpG89uN/gvSQXMhSjWQJntmckV30wcoxDiUOqnluO5qgRNNEL10aDfMZKrR3zjRIAbPrp4QDUEGx3ATMupeiVxWSGURcG4XmLs0hy+Cux5P44+hi0a+3dV6V6B+P2CWjegnG0YLIM+jBzkdzHWSgubeM0JTVuej0ZcaOiKuk1p0UiDd+1Aguj1yG9W01jRThzB6zDcv6kawqtPNNrfZW+TdPSFvb0osHCfyd75RedD6EekjyQAiEl5N36QstIELZGN/XdI7OSh0aFP+DstMxduKT0DloPhbULef/h8G6YeQjYZHZnmu0kOKD3dPOZaaATbIZEO7eS9NoWTzHXjnuYIKYqKa5V1px+GXq3avkARLrhWQclrF3Hxk5n6TJisi1VB1BG8TqtMAa1EJ+23RTm68=
  - secure: DnvnOXvpVKyitoNYYLdKQG9ThN3h+/gelw+VXjLQmSwVtC2qJPxMfRKOd6itybP/V+m9RYkF1rzV8CtYHN1Rh2ulto1Ih9Ffup584VC6KS6P3n8MP2GUA/cXt5sm1946z1qROJ0GjpZX7vyGT8aMfLXoo4ViHqBzw2bSKmqnMtbFG1sqhM4MXXACOy5EYiRNwzL1B0bfmU3qp/cd2t6T2SY/euKXzbwz17oosM+6fRMAxcnfM2pdoTVUrugosTDAusJG/kiGZBqMk91INmjUvOyrwKcshgrvVcUGZD781JXIU8WycoXpAbWm4CboATT5vNxOvBoyNWb++nmPHwMvuacSl33q7a4MpbK2p249o+G+NcVR2y9Kl658OxZV0ORdvGIv+XZVEk1Ky/xs+5LF9PC5TJeZZmQ7OPbRifX5BVqY1t0QVuw3fdPGznfOeQD/ubtGi45gOwxk3yaEmewIQroBfC/Ee87HUuP4U8yzWu4alcoqjKmjNoFwfuzoZLwVlrBafq1Ru4tY2At+NekdCCe5ELnelTVt7g0MeFXrmyz2iORa8pNlObj5m8jETMgJN50IdlboT8/BWAJySuqn2u6gLoqAFme6QFhvR3CCvVn/Js7kZPkOJio7M/6JRRUGCztprm5XBvAnr33gV4FLukYd2FkHz27FL+xe08qQLQM=
