language: node_js
node_js:
- '8'
sudo: false
before_script:
- npm install -g quasar-cli
script:
- quasar lint
- quasar build
before_deploy:
- openssl aes-256-cbc -K $encrypted_6471c10cdc2d_key -iv $encrypted_6471c10cdc2d_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: sh ./deploy.sh
  on:
    branch: master
env:
  global:
  - secure: Owh6Xf+/IFGrKZBIiYnd8t0szV3soLvkuG2+xb0xx9mBJ6x/qyVJIfQ5DQ8IPsoetCZnbN3gsivcw4JPw/P1otSp6cf8klv80dHw9QvOURRkArojOp0HPKsXfr0hdQ896Sl1Pvg26S/Hz8Rjrq/Db2W5fxHypRukOM61fUOj+YLCUqYBLS5dy+x9lZRte89nMqkpEeR8kkUUNmCHUrR6QAbDoq/Dss/60Iw8SOdtutZqLLzjnVJWmFQyRgXHXTaFjOFBdlVzxAjJ6GSonrIzCWXJL08T0rQoTMYPIIjmVW7ws3HgqBvPTkMTTeG/uRFLQKb2jB5bsqm9pzv8KKHTWFw2CgJQTaLfA9tO9sKTHo9CzvrUZa711+m6wO2SXZXt9JpI4zHFY9wCED9NytCxng22o9I3UsYhLw8DAqABzNvXEMgckdlyl1XNAFcKcXRSEBVQkfg86UY3oeoz+3iZhkGBnds2XKp5M0P6zCndcIRoXTrzGQgmWvMFfDTjV3xgp8YiBe9aG9lvgzG6djhse+W3ABaqSvlwp+QTjZS+hkFbKbNBQOiPHpu7mW5ffb088XUumFdhHzJjhzX8xqT0L0ePodKrh3tMHp0ZjlQzggG4LadLQ6YzlEusm8Ys5eXioRkihOdnxRLzFAdnWpkdppI/yEjwRUq9UaEdcCLbLFY=
  - secure: gAs8BbmRCZOoDV8QghEMe7NSGTZY1Kl+wvJsEYisG+FXwyO68ExWRCX1N9zMvJprz5gsUnHxZHeWWTg1SaL4aGBeKAZCigfRt61VTQxnTNkTYk/FpiSk0jaUq95czWxgRa1Pt9UHnXHJZS7UciMDvgU42tJjiMZwNLJGjbRH1yP46rCouWf8q88m3ZVxW/czau1RH7YE6MNfQ8409Xd4wYJN8ph7cEmdtziQ3qAFcBjLU/5a8Uwu1ZtRghOsLkImlugHQ5wMRYafCvhlPC6y8lkpYT7xU+xaWmADMrniWYhnoNd+lxMcCumYUeKtPgBJXqwcY8VD7G6mwM0z868FwLjpxSCV+XQFAL26hD9VZzH/5KegEPVrRz2Yjc7FnwRbS3kHQqNb8Ufja1OtEqNAgEmeKjJVWOVj69+j56jNpWmfm1B3LdrFvpjc53dVjkoZlsOWBhbE1vtjMIXn6T+r9DVF04K/VqEfRLyPMaoQt5OX/G9SZbxfd1sMhIi3l4BUc+07r57PWJxuqDQgotFnIj6n18NQM/+oUmpa/xnXP2wq02rgtANVmdRDgy/SPhCT417U9IH6PUF6sjOUzCYNTsnswra1nF+kzAP0LK9f5zZgd1MEzIlStijTuyJAiguhAC0uPWm9WQpO7Ab8Pw9ltNVm7gYsSm+Ce0lUxDOhv9A=
  - secure: V1Qv+Z9IMSeJ444y9HzgkuHtf2X9UbwgCS2HlNN8mol5DgNR1tmcp9Td3JNhLxfNeUzm2Kv2ggBesVqjp6Dc9q/kMPWJNSI6Cbp6O2OJpNR+q95md+z+dAThone2d3SDbIgbHamBfWHQ7+g6eMqwg15F3yv7yLwjp91cSxDm/c8BZ9SNy35xQwUwR30D+gaDxvcmjhZl6VGtojaGfzi/4CDrOR8DJay71lkdp+BRQ45pUYTE3VzvPqKPguyCyV59jH4fVDqf6Qsi+Km3jN7iVx1FW8L1jbG9cRwXyUi871xgUZge3Gfv0sS/sK9o6/DeFVcXatLhmL6/xeTAvpeRtOZNKasWpwzpJEethZODssRLarykN6EtMgbvz539GIvYo5S1jfAHWPwLQQpNzjbwjc83CO5cf8z5dXzF2HNXJCy7YOCthxts74DxdHn3ZtKGYHrDp6+I3R9mrAJ+XrZav30eWTTAYGPP4Cp3w1VznKwPQmgO9CWmVdvX8JEOW0n3MYeXFfd3MkuHgdT2MgZf6BAYzzTdpsZkJcT0rXHEYnvQuQ7K6Wl9ojlaOhhFuVsDFF02GhsBLQW2j2Vq7mhwBDSvybuJPo0P3+REKSWVrlERGzCcwMGD6cGTxNFYbaJ5zBYKohsFXKO6ZiePPn9T0PD47GztDcPjw+79UFGipzY=
  - secure: jzqJmgTOqq5TZl3fROOvv078le4qfhcsnet3uLENMq35KxZVg9EvK09lhXv6yxXQYZspqGkUPIYbIUvPzZBCDqjvE0iFo3zbADEM3Dv2J/Je66winkRclEpCf2der+Mqlo7UAUCJM86ZCy5KvVBI6Sx0YQVoujcaFtKgNk69H1ccjwdIPF3tK50Bw+1sLsECOQR4TaZl+2yS8q63GTiAyuA9rvZDMMUEQEW6SDGXATWdkoUP8QucT5pusHchndl+6nCClOeiwEADVdqSwQT1U4yQHvZBj/D1/M5Bt7rp/vZRaE6xoFkFNmx6NLC0OAdlNYzV0T4iKu3ZhTD8aU6CcTCMVt1wrYHshUTbyZYLyeTwFce6p5HJLYbHmBMgxCYaYPbryGuhH2Yt3jxIaaeuwDuEf2kEzdFQr6kGDS9BN86nqbbVlbKGoiqyZB9T6EtHUgczmqAwY7dwQxLCOG1uvFgR7PmimapXby6NTH4D2jTAYv5doKoBIrya0bgtS1gNHUC0/u8M9TERycRSW9sHkMscJJviuX2D361oImGhsQyNWquFuQMeOYNOSXGPiJVebeeQhgOnY5/vA8acg72w7UednaaCr9imsDQY3/D/vRYntWXR+AJYMaDC3VQQTi5bYVNs6xPgVehegoLlK9VPCfl2pKDlhYnpsbW6Uus6Bvo=
