language: node_js
node_js:
- '8'
sudo: false
before_script:
- npm install -g quasar-cli
script:
- quasar lint
- quasar build -m pwa
before_deploy:
- openssl aes-256-cbc -K $encrypted_6471c10cdc2d_key -iv $encrypted_6471c10cdc2d_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: sh ./deploy.sh
  on:
    branch: master
env:
  global:
  - secure: UhGk+Jsovt/h+fQD+OJ9PiNWK4AuwhB++RaYd5cN8MSu+PgJxUDc3MOxGeZNfBGrWHUi2WNRcTN9RWEetz2RaVs8/cT5QvOJ97zylYFEILH0MkCb95dsTzHn+RBh2iSTTmQWHoK8TguIQzmefW/nhlhba5gBZz2lhotPWSEmknIAOe4nkR9cdfMaEcs0AXJZUAKakbVkbaHogXh9lP7+Qv9JQQnwtduX/99A2txJoHT3gHd6OijZGCMHj5lqT+/NuAg8yiTRgGu0mYxgfwlgdctQ/o15o4E1MvOknTuOUtt/JxrTCfKpnMbAKWkzieEr+5gyB9pEqCBiMjcNvmBKnXIRQdmXe83RU/zwTOFw/j+jNEHdLirmE+BjZbMwVhX07wUHflBw9tCoI73RvuJdDcHxdpRQM7eg3PrIS6bRzsEr+Lv/swdBich42VLfiiyyryIApIcvetajQitut0NSohpDpoleuBDiCWbVQkiariYg6yw2ncbpXtIW2XQ9g6h7aBCMjedQP6wkDVa+QaXO6zTvajr3UhVhZbukuvefE0eCDKesBYFEJbUO2sTzm50MYGCW0LhvHj1AR5bzwKrLepObplBk9WsTnB8Z6zzokujI1A++OcYfi+AzSktFFcn5QHjZRGW9ruiYnkpNbtroBYb02krdJwbUzWH7YKzAFaY=
  - secure: Gejzp6aOhNUm+LfbdGvVwdiqY+EeiOx1dbxjeUajhcS+fRzUmv653h8hpj+z+P9frgebhOHH0/DgFetwzC6APJqMJb232LXjTYTihwByOYevfEFF6xhWMokB1FM++wYKI4fXqkDRKlG5OCwuGj0BfR0TErwpUcI6umohBBUTz/mFKmhFpsiAGYSiZsnW70BNDkFAKfezWaOYdXrx7rGHLrbXFPZ+p98CDdpCSZVQcxrOoLrxtDRDxHF6jfT4UMbYwR9l2BiYRBASLCAyQURLEjShX+2VvOs5FspAzdqT60KHO3dSjob0Qs95OnJ1LbjW6654b3y0ERptgy3X7DRQaIKw5ql54le71H/XkjYCq7MY7gZHIIu+1WZbgdMReCqk0DpQ1C1SgPOBOyIpn3+N9MdvWdV1F6mxmciMe5dH9gYvUFT3IkMMaTFkMNyAh+DQ2An1MDu7W3i4338RzA+BxOfoIP+ydD+xTgh7AX4pjcGj0noQg28CgZ79HgF2doOXN19/XXNQcijEKOpH6lMWhkIUxgTg8TXnzliY1DDuoUiv/NRRGICIvzp+AO9G9VteNTZORwqtTGFkaQklJUUfUVgrAfrjSUoMKCYNYfa81gARISMr+3gCuJceKVkuZLqx/XisOzR5MZYgUbncp6RfQ5AkLzbRb3CLwJI5/sloJzQ=
  - secure: HwgDFaUDd7tf+ZffkExfxleT7ezQKp4v4EctssGQqT6ROvcOcmcrcRcS09ZOGTXHIggi+3xL+v4uLce6hgxdOMtT74SgxpTsQt2wF7cGOWu3bgBG4iOKN5nM5S25hLhcwJvfpbMLlB2yLplUMMjQCMtktLbKhz4dhh9aDCAlYkRnaQZqCgRgEbaef4AzfyJqNuwuccdrMG37+mdKw2k0fdtxuVzIQNl1lFXFTPz4+e7jEHRsqShSZxY9WW5ihzCQuwHBAh70/ToTT2xiLD04AEX3GWW9mmiAMQp+ecUrQE9SZCnVWnDvgT6dlkOjUQZhw7oGMlzvh6ZHRyrjRIFPjA7GMn8jcKi+u83idx5zb1Rem+BzVSQHXh1SqWZ/bXELxeZ75GFiR/Z3IwyqW3d4mmpFJcNHu6nwOdDsmaS3kXZoQVIy6Bao9V/+eUh244CEelFiagoASghd60uDdhbnIpo0Kj11jFVIFixHqVyIweCtKams7XfENsNTlPyFBWBkqIVRbe6KcB4tVkwHgax53I/YuemiqFHmIopWNwvxYJ0FmfHLmL5woyKY3/1A/AJtAAh0PsK80TBty/xzqylzqEv7EK1NUENAMFlAwnOLNn2f7qlVhd6A7DAx6T/S8mbBw4CXFw2le/CLkJIqV/WJ0YETUP/xYc2ZxxYfbQR9NFE=
  - secure: KncFphnnRM/pAFDbMa2EYg+d2DBNOif2rchtx/FRIvyFqXKCZYeQtELwLdr46AtocaceBkNBSZQF97h2EFCm6ZsxXGH4YO77SVSwSbgDcwUts5BAAj41+LLIKBt6Nrx4M1GFvEXUiCFEqmr6tUWKY5t9H1IXsXYnpRSGy1hfTeehrzeDRvS6Vkq5j2UsOH2g6t8aVNcAKlIdj90lb3ExVLXMbMvQMVHgJGXV30lRkWe61UI64axgWzlvnxrFnyYue++3ml1akB7lFm4nEV4NceeB4n6iPEUAznScHVufCD5w97upFfIyWgiNSSKA/lSaOsVza29LXlHEam+dp61HC+EUF92NNb9qj45/tYgO/I4T4vrjWc/BA+J3zGTN8poUMqPpv/RkDS6/G9OyWbVBVmdwQ94nSZ2OAtlV/GrMEk/tJ0TxNO3KP/mbY540FgrVq6VaOSTOt275vs61RrPjgOKEnhPFYdn0edQJWaxjnqZhzKJizkys1ZIOD8tGXYeF7oHH+Qrqa2AH89E2cXN74vjELdHW+5oy2U68ncA5IB0f1AJ/HmanTVWDX+2OWpVBh/AgtzG6sL9Oc8ea/O7d/69HAYNrhXSEkJHronIQKfcFLZsntyTF6/IRnxlRaZ9OjKLhU+Fc88UKOGWDJXlzntDQzgfT9ZrYKE8nvFDlO9U=
